---
site_name: Shenbi
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

