# spec #48 C34 R2 (F433/F101 残留/F457/F446): cli G4 project_dir vs rd
# separation, bughunt/clean rd wiring + structured ValueError guard.

from pathlib import Path

import pytest

from shenbi.gates import cli


def _run_g4(monkeypatch: pytest.MonkeyPatch, tmp_path: Path, *argv: str) -> dict[str, object]:
    captured: list[dict[str, object]] = []

    def fake_emit(payload: dict[str, object]) -> None:
        captured.append(payload)

    import shenbi.cli_utils

    monkeypatch.setattr(shenbi.cli_utils, "emit_json", fake_emit)
    monkeypatch.setattr("sys.argv", ["shenbi-validate", "G4", *argv])
    cli.main()
    assert captured, "no JSON emitted"
    return captured[-1]


def test_g4_generative_distinguishes_project_dir(monkeypatch, tmp_path):
    # F433: PWI findings live under the REAL project_dir (writer anchors
    # project_dir/audits), not rd. With rd != project_dir and PWI jsonl in pd,
    # G4 must surface G4.ac/av checks. RED today: cli passes project_dir=rd.
    pd = tmp_path / "pd"
    rd = tmp_path / "rd"
    rd.mkdir()
    pd.mkdir()
    # PWI jsonl generated by the real writer code path (G0.9):
    from shenbi.pipeline.dispatch_helper import _write_parsed_outputs

    _write_parsed_outputs(
        "",
        ["audits/chapter-3-x.md"],
        pd,
        skill=None,
        parsed={"audits/chapter-3-x.md": "<无 verdict 短文本>"},
    )
    pwi = pd / "audits" / ".integrity-findings-3.jsonl"
    assert pwi.exists(), "real writer path must produce the PWI jsonl"
    # chapter file in rd so the checker runs on chapter 3
    (rd / "chapter-3-x.md").write_text("第3章\n\n正文。", encoding="utf-8")
    result = _run_g4(
        monkeypatch,
        tmp_path,
        "chapter-drafting",
        str(rd / "chapter-3-x.md"),
        str(rd),
        str(pd),
    )
    ids = [c.get("id") for c in result.get("checks", [])]  # type: ignore[union-attr]
    assert any(str(i).startswith("G4.a") for i in ids), f"PWI checks missing: {ids}"


def test_bughunt_relative_with_rd_structured(monkeypatch, tmp_path):
    rd = tmp_path / "rd"
    rd.mkdir()
    (rd / "notes.md").write_text("note\n", encoding="utf-8")
    result = _run_g4(monkeypatch, tmp_path, "bughunt", "notes.md", str(rd))
    assert isinstance(result, dict)  # structured, not uncaught ValueError
    assert result.get("status") in ("PASS", "FAIL")


def test_bughunt_relative_no_rd_structured_fail(monkeypatch, tmp_path):
    monkeypatch.chdir(tmp_path)
    result = _run_g4(monkeypatch, tmp_path, "bughunt", "missing-relative.md")
    assert result.get("status") == "FAIL"
    assert "invalid file path" in str(result.get("error", ""))


def test_clean_relative_no_rd_structured_fail(monkeypatch, tmp_path):
    monkeypatch.chdir(tmp_path)
    result = _run_g4(monkeypatch, tmp_path, "clean", "missing-relative.md")
    assert result.get("status") == "FAIL"
    assert "invalid file path" in str(result.get("error", ""))


def test_f446_relative_json_rd_cwd_never_crashes(monkeypatch, tmp_path):
    # F446 regression: relative json + rd + CWD != rd → structured outcome.
    monkeypatch.chdir(tmp_path)
    rd = tmp_path / "rd"
    rd.mkdir()
    (rd / "rev.json").write_text("{}", encoding="utf-8")
    result = _run_g4(monkeypatch, tmp_path, "chapter-revision", "rev.json", str(rd), str(rd))
    assert isinstance(result, dict)
