"""Verify documentation accuracy.

Scans markdown files for code-span references to file paths (e.g.,
`tests/validate-gate.py`) and verifies those files exist. Catches the
most common doc drift: stale path references.

Coverage (spec #63 F957 widening): all root-level markdown plus the full
docs/ tree (excluding generated/frozen areas — docs/skills is generated by
`just generate`; docs/superpowers holds frozen audit history whose links
are covered by the C17 internal-links defense line).

Not a substitute for semantic review — only catches missing-file drift.
"""

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

GENERATED_OR_EXEMPT = {
    "docs/skills",  # just generate 产物（sync-contracts 生成 skill 页）
    "docs/superpowers",  # 工作态文档（archive/audit-runs 历史冻结；C17 internal-links 防线覆盖）
}

DOCS_TO_CHECK = sorted(str(p.relative_to(REPO_ROOT)) for p in REPO_ROOT.glob("*.md")) + sorted(
    str(p.relative_to(REPO_ROOT))
    for p in (REPO_ROOT / "docs").rglob("*.md")
    if not any(p.is_relative_to(REPO_ROOT / e) for e in GENERATED_OR_EXEMPT)
)

ALLOWED_MISSING: set[str] = {
    "deps.json",
    "plans/chapter-N-plan.md",
    # 结构示意占位（AGENTS.md 目录树 "python3 tests/X.py" 反例）
    "tests/X.py",
    # 冻结历史：CHANGELOG 追溯条目引用的旧归档文件名（append-only 不回改）
    "docs/superpowers/specs/archive/2026-06-15-p-1.e",
    # roadmap「deferred hook」条目有意引用尚未创建的文件
    "tests/build_registry.py",
}

# 多字符 codespan，允许空格分隔的中英路径 token 与参数化形态（spec #63 F957）。
# PATH_TOKEN 要求带扩展名（`.\w+` 结尾）——无扩展名目录引用（如 `docs/getting-started`）
# 不在此防线内（有意收窄：避免把自然语言 token 误判为路径；目录级断链由 C17 的
# markdown-link 防线覆盖）。
CODESPAN_PATTERN = re.compile(r"`([^`\n]+)`")
PATH_TOKEN_PATTERN = re.compile(r"[.\w][\w./-]*\.\w+")

# 仓库内顶层前缀：codespan 路径命中这些前缀时必须存在于仓库根。未命中前缀且
# 非 doc 相对链接的 slash 路径（truth/、world/、outline/ 等运行时 truth 树）与
# 裸文件名（SKILL.md、shared.py 等模块提及）不按仓库根校验——它们属于
# pipeline 项目树或示意名，非仓库路径引用。
REPO_PREFIXES = (
    "tests/",
    "tools/",
    "docs/",
    "skills/",
    "src/",
    "scripts/",
    ".github/",
    ".codex-plugin/",
    # plans/ 仓库根不存在，但既有 ALLOWED_MISSING 条目（plans/chapter-N-plan.md）
    # 依赖其严格校验语义，保留（audit-T7 I 裁决）
    "plans/",
)


def _validate_targets(doc_path: Path, candidate: str) -> list[Path]:
    """Map a codespan token to the file paths it must exist at (may be [])."""
    if candidate.startswith(("./", "../")):
        return [doc_path.parent / candidate]
    if candidate.startswith(REPO_PREFIXES):
        return [REPO_ROOT / candidate]
    return []


def extract_paths_from_doc(doc_path: Path) -> list[Path]:
    """Extract code-span file path references from a markdown doc."""
    if not doc_path.exists():
        return []
    text = doc_path.read_text(encoding="utf-8")
    paths = []
    for span in CODESPAN_PATTERN.finditer(text):
        for candidate in PATH_TOKEN_PATTERN.findall(span.group(1)):
            paths.extend(_validate_targets(doc_path, candidate))
    return paths


@pytest.mark.parametrize("doc_relative", DOCS_TO_CHECK)
def test_doc_references_existing_files(doc_relative: str) -> None:
    """Each code-span file reference in docs must point to an existing file."""
    doc_path = REPO_ROOT / doc_relative
    assert doc_path.exists(), f"{doc_relative} missing (F731: dead skip — doc set is fixed)"

    missing = []
    for referenced in extract_paths_from_doc(doc_path):
        rel = referenced.relative_to(REPO_ROOT).as_posix()
        if rel in ALLOWED_MISSING:
            continue
        if not referenced.exists():
            missing.append(f"{doc_relative}: references `{rel}` which does not exist")

    assert not missing, "Documentation references missing files:\n" + "\n".join(missing)


def test_chapter_file_format_doc_exists():
    doc_path = Path(__file__).resolve().parents[2] / "docs" / "framework" / "chapter-file-format.md"
    assert doc_path.exists(), f"Expected {doc_path} to exist"


def test_chapter_file_format_documents_meta_blocks():
    doc_path = Path(__file__).resolve().parents[2] / "docs" / "framework" / "chapter-file-format.md"
    assert doc_path.exists(), "chapter-file-format.md missing (F731: dead skip)"
    content = doc_path.read_text(encoding="utf-8")
    assert "META" in content
    assert "<!--META-BEGIN-->" in content or "META-BEGIN" in content


def test_chapter_file_format_documents_stripping_method():
    doc_path = Path(__file__).resolve().parents[2] / "docs" / "framework" / "chapter-file-format.md"
    assert doc_path.exists(), "chapter-file-format.md missing (F731: dead skip)"
    content = doc_path.read_text(encoding="utf-8")
    assert "strip" in content.lower() or "shared.py" in content


def test_chapter_file_format_states_meta_not_prose():
    doc_path = Path(__file__).resolve().parents[2] / "docs" / "framework" / "chapter-file-format.md"
    assert doc_path.exists(), "chapter-file-format.md missing (F731: dead skip)"
    content = doc_path.read_text(encoding="utf-8")
    assert "not part of" in content.lower() or "not prose" in content.lower()
